### ISSUE TITLE
Possibilities of using a buffer node

### ISSUE THREAD

**Issue by it-fm** [dacunni/stlloader#3]
Is there a way to use a template loaded on a buffer node with this module? I'm trying to do this using node addon + nan api

**Comment by dacunni** [comment]
I don't do any node development, so I don't have experience with doing so. But from looking at it, it seems like it might be possible. Is there something about the stlloader API that is making it hard to use with none addon + nan?

**Comment by it-fm** [comment]
Thank you, I did it.
